replicaCount: 1

image:
  repository: "980921758549.dkr.ecr.ap-south-1.amazonaws.com/automarkly/emailservice-worker"
  tag: "1.3.0-19"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceAccount:
  name: "email-service"
  roleArn: "arn:aws:iam::980921758549:role/email-service-email-service-role"
  annotations: {}

env:
  AWS__SQS__QueueUrl: "https://sqs.ap-south-1.amazonaws.com/980921758549/email-service-email-queue"
  AWS__Region: "ap-south-1"
  Email__FromAddress: "email@myname.click"
