controller:
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 200m
      memory: 180Mi
  admissionWebhooks:
    enabled: true
    failurePolicy: Fail
    timeoutSeconds: 10