apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: "https://fluent.github.io/helm-charts"
    chart: fluent-bit
    targetRevision: "0.21.7"
    helm:
      valueFiles:
      - $values/values/infrastructure/fluent-bit-values.yaml
  - repoURL: "https://github.com/sara-golombeck/gitops-email-service.git"
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2