apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "email-service" }}
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: AWS__SQS__QueueUrl
          value: {{ .Values.env.AWS__SQS__QueueUrl | quote }}
        - name: AWS__Region
          value: {{ .Values.env.AWS__Region | quote }}
        - name: Email__FromAddress
          value: {{ .Values.env.Email__FromAddress | quote }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
