apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: infra-apps
    app.kubernetes.io/managed-by: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sara-golombeck/gitops-email-service.git
    targetRevision: HEAD
    path: argocd/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
  ignoreDifferences:
  - group: "*"
    kind: "Application"
    jsonPointers:
    - /spec/syncPolicy/automated